name: C/C++ CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: build
        run:  chmod +x ./tasks/build.bash && ./tasks/build.bash
      - name: test
        run:  chmod +x ./tasks/test.bash && ./tasks/test.bash